name: bladi_go_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.5
  bcrypt: ^1.1.3
  fluttertoast: ^8.2.12
  provider: ^6.1.4
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  http: ^1.3.0
  http_parser: ^4.1.2
  image: ^4.5.4
  googleapis_auth: ^1.6.0
  cloud_functions: ^5.3.4
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/bg.png
    - assets/images/
    - assets/icons/Flache.svg
   

  fonts:
    - family: BelieveIt-DvLE
      fonts:
        - asset: assets/fonts/BelieveIt-DvLE.ttf
